ALTER TABLE club DEFAULT CHARSET utf8mb4;
ALTER TABLE `match` DEFAULT CHARSET utf8mb4;
ALTER TABLE player DEFAULT CHARSET utf8mb4;
ALTER TABLE playerinclubseason DEFAULT CHARSET utf8mb4;
ALTER TABLE stadium DEFAULT CHARSET utf8mb4;
ALTER TABLE `user` DEFAULT CHARSET utf8mb4;
ALTER TABLE usermatchreview DEFAULT CHARSET utf8mb4;